### List all books
GET http://localhost:8000/books

### List book details with title
GET http://localhost:8000/books/Title Three

### List book details with book id
GET http://localhost:8000/books/id/4

### List book details by published year
GET http://localhost:8000/books/published_date/1995

### List book details by category
GET http://localhost:8000/books/?category=science


### List book details by auther
GET http://localhost:8000/books/byauthor/?author=Author Two


### List book details by auther and category
GET http://localhost:8000/books/Author Two/?category=science

### add new book details
POST http://localhost:8000/books/create_book
Content-Type: application/json

{
    "title": "Title ten",
    "author": "Author One",
    "category": "mac",
    "published_date": "2021"

}

### update book details
PUT http://localhost:8000/books/update_book
Content-Type: application/json

{
    "title": "Title ten",
    "author": "Author One",
    "category": "science",
    "published_date": "2022"
}


### delete book by 
DELETE  http://localhost:8000/books/delete_book/Title Two
Content-Type: application/json

{
    "title": "Title ten",
    "author": "Author One",
    "category": "science"
}